matrix:
  include:
    - os: linux
      sudo: required
      dist: trusty
      language: python
      python: "3.4_with_system_site_packages"
      env: PACKAGES="xvfb libgstreamer1.0-0 libgstreamer1.0-dev gstreamer1.0-alsa gstreamer1.0-clutter gstreamer1.0-fluendo-mp3 gstreamer1.0-libav gstreamer1.0-nice gstreamer1.0-plugins-bad gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-ugly gstreamer1.0-pulseaudio gstreamer1.0-x gir1.2-gtk-3.0 gir1.2-gst-plugins-base-1.0 python3-gi python3-gi-cairo python3-gst-1.0 python3-pytest" PYTHON="python3"

install:
  - sudo apt-get update -q
  - sudo apt-get install --no-install-recommends -y $(echo $PACKAGES)

script:
  - xvfb-run -a "$PYTHON" -m pytest
